# This Playbook is designed to be ran on-demand when DB recovery is needed
# Execute ora_dr_setup.yml playbook to setup the dr host before running this playbook
# Ensure that /etc/oratab, /etc/oraInst.loc files have been copied over from pirmary server to dr server 
---
- name: Oracle DB Restore
  collections:
    - netapp.ontap
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - roles/ora_restore/defaults/main.yml
    - roles/ontap_setup/defaults/main.yml
  roles:
    - role: ora_restore
  tags:
    - ora_restore
    
- name: Mount and Verify Oracle Volumes
  hosts: dr_oracle
  gather_facts: True
  vars_files:
    - roles/ontap_setup/defaults/main.yml
    - roles/dr_ora_vols/defaults/main.yml
  roles:
    - role: dr_ora_vols
  tags:
    - ora_vol_mount

- name: recover Oracle DB to desired recovery point
  hosts: dr_oracle
  gather_facts: False 
  vars_files:
    - roles/dr_ora_host/defaults/main.yml
    - roles/ora_restore/defaults/main.yml
  roles:
    - role: ora_recovery
  tags:
    - ora_recovery
