#This Playbook is designed to be ran on-demand when DB recovery is needed
- name: Oracle Linux Setup and Storage Config for Oracle
  hosts: dr_oracle
  gather_facts: True
  vars_files:
    - roles/dr_ora_host/defaults/main.yml
  roles:
    - role: dr_ora_host
  tags:
    - linux_config

- name: Oracle DB Restore
  collections:
    - netapp.ontap
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - roles/ora_restore/defaults/main.yml
    - roles/ontap_setup/defaults/main.yml
  roles:
    - role: ora_restore
  tags:
    - ora_restore
    
- name: Mount and Verify Oracle Volumes
  hosts: dr_oracle
  gather_facts: True
  vars_files:
    - roles/ontap_setup/defaults/main.yml
    - roles/dr_ora_vols/defaults/main.yml
  roles:
    - role: dr_ora_vols
  tags:
    - ora_vol_mount

- name: recover Oracle DB to desired recovery point
  hosts: dr_oracle
  gather_facts: False 
  vars_files:
    - roles/dr_ora_host/defaults/main.yml
    - roles/ora_restore/defaults/main.yml
  roles:
    - role: ora_recovery
  tags:
    - ora_recovery
