---
- name: Install requirements for running the playbooks
  hosts: oracle
  connection: local
  gather_facts: False
  tasks:
    - name: Install python libraries
      pip:
        name:
          - netapp-lib
          - xmltodict
          - jmespath
  tags:
    - requirements_config
