##############################################################################
##############################################################################
- block:
###############################################################################
################### Task for creating cluster peer ############################
    - name: Create cluster peer
      netapp.ontap.na_ontap_cluster_peer:
        state: present
        source_intercluster_lifs: "{{ src_inter_ip }}"
        dest_intercluster_lifs: "{{ dst_inter_ip }}"
        passphrase: "{{ passphrase }}"
        hostname: "{{ src_cluster_ip }}"
        username: "{{ src_cluster_username }}"
        password: "{{ src_cluster_password }}"
        peer_options:
          hostname: "{{ dst_cluster_ip }}"
          username: "{{ dst_cluster_username }}"
          password: "{{ dst_cluster_password }}"
        encryption_protocol_proposed: tls_psk
        validate_certs: no
        use_rest: auto
        https: true
      register: cluster_peer  
      tags:
        - ontap_cluster_peer

###############################################################################
################### Tasks for create vserver peer #############################
    - name: Create vserver peer
      na_ontap_vserver_peer:
        state: present
        peer_vserver: "{{ dst_vserver }}"
        peer_cluster: "{{ dst_cluster_name }}"
        vserver: "{{ src_vserver }}"
        applications: snapmirror
        hostname: "{{ src_cluster_ip }}"
        username: "{{ src_cluster_username }}"
        password: "{{ src_cluster_password }}"
        dest_hostname: "{{ dst_cluster_ip }}"
        https: true
        validate_certs: false
      register: vserver_peer
      tags:
        - ontap_vserver_peer
  rescue:
    - name: Failure
      fail:
        msg:
        - Create cluster/vserver peer failed
        - Possible troubleshooting steps:
        - 1. Check if ONTAP API is reachable
        - 2. Check credentials
        - 3. Check source cluster IP
        - 4. Check destination cluster IP
  tags:
    - ontap_create_clusterpeer_svmpeer
