---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Intercluster Configuration for existing intercluster lifs
      include_tasks: create_clusterpeer_svmpeer.yml
      tags:
        - ontap_cluster_peer
        - ontap_vserver_peer
        - ontap_create_clusterpeer_svmpeer     

    - name: Snapmirror Setup
      include_tasks: create_dest_snapmirror.yml
      tags:
        - ontap_disable_default_snapshot_p
        - ontap_unlock_svm_admin_p
        - ontap_unlock_svm_admin_s
        - ontap_create_target_vols
        - ontap_snapmirror_create
        - ontap_snapmirror_policy
        - ontap_snapmirror
