- block:
    - name: Obtain Oracle Consistency Group all Volumes
      set_fact:
        src_cg_all_vols: "{{ src_cg_all_vols + [item.vol_name] }}"
      with_items:
        - "{{ src_orabinary_vols }}"
        - "{{ src_db_vols }}"
        - "{{ src_archivelog_vols }}"
    - debug:
        msg: "Source Consistency Group all Volumes {{ src_cg_all_vols }}"

    - name: Resync ONTAP/ONTAP SnapMirror
      netapp.ontap.na_ontap_snapmirror:
        hostname: "{{ dst_vserver_mgmt_lif }}"
        username: "{{ dst_snapadmin_username }}"
        password: "{{ dst_snapadmin_password }}"
        state: present
        relationship_state: active
        source_endpoint:
          cluster: "{{ src_cluster_name }}"
          path: "{{ src_vserver + ':' + item }}"
        destination_endpoint:
          cluster: "{{ dst_cluster_name }}"
          path: "{{ dst_vserver + ':' + 'dr_' + item }}"
        relationship_type: extended_data_protection
        https: true
        validate_certs: false
        use_rest: always
      with_items:
        - "{{ src_cg_all_vols }}"
      tags:
        - ontap_snapmirror_active
