- block:
    - name: Obtain Oracle Consistency Group data volumes
      set_fact:
        src_cg_dat_vols: "{{ src_cg_dat_vols + [item.vol_name] }}"
      with_items:
        - "{{ src_orabinary_vols }}"
        - "{{ src_db_vols }}"
    - debug:
        msg: "Source Consistency Group Volumes {{ src_cg_dat_vols }}"

    - name: Get Timestamp
      uri:
        url: https://{{ src_cluster_ip }}/api/cluster
        user: "{{ src_cluster_username }}"
        password: "{{ src_cluster_password }}"
        method: GET
        validate_certs: false
      register: ontap_time

    - set_fact:
        readable_format: "{{ ontap_time.json.statistics.timestamp }}"
         
    - name: Consistency Group Snapshot
      netapp.ontap.na_ontap_cg_snapshot:
        hostname: "{{ src_cluster_ip }}"
        username: "{{ src_cluster_username }}"
        password: "{{ src_cluster_password }}"
        state: present
        https: true
        validate_certs: false
        use_rest: always
        vserver: "{{ src_vserver }}"
        snapshot: "{{ cg_snapshot_name_prefix + '.' + readable_format }}"
        volumes: "{{ src_cg_dat_vols }}"
        snapmirror_label: "{{ cg_snapshot_name_prefix }}"
      tags:
        - ontap_cg_snapshot
    
    - name: Snapmirror Update for DB and Binary Oracle Volumes
      netapp.ontap.na_ontap_ssh_command:
        hostname: "{{ dst_cluster_ip }}"
        username: "{{ dst_cluster_username }}"
        password: "{{ dst_cluster_password }}"
        command: "snapmirror update -destination-path {{ dst_vserver + ':' + 'dr_' + item }} -source-snapshot {{ cg_snapshot_name_prefix + '.' + readable_format }}"
        accept_unknown_host_keys: true
        privilege: admin
      with_items:
        - "{{ src_cg_dat_vols }}"
      tags:
        - ontap_snapmirror_update

  rescue:
    - name: Failure
      fail:
        msg:
        - Create destination volume for SnapMirror failed with error
        - Possible troubleshooting steps:
        - 1. Check if ONTAP API is reachable
        - 2. Check if variables defined adhere to the guidelines
